openapi: 3.2.0
info:
  title: ⚙️ API specifications Document check API
  description: Dotfile public API documentation
  version: v1
  contact: {}
servers:
- url: https://api.dotfile.com
  description: Production environment
security:
- DotfileAPIKey: []
tags:
- name: Document check
paths:
  /v1/checks/document:
    post:
      operationId: document-create-one
      summary: Create a Document check
      description: 'Create a Document check. Use Upload a file to get an `upload_ref`.


        ---


        #### See also

        Learn more about Document checks

        Learn more about Files'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
              - $ref: '#/components/schemas/DocumentCheckCompanyCreate'
                title: Document Check Company Create
              - $ref: '#/components/schemas/DocumentCheckIndividualCreate'
                title: Document Check Individual Create
            examples:
              companyDocumentType:
                summary: Create Document check on a company
                description: Using the body parameter `DocumentCheckCompanyCreate`
                value:
                  company_id: de0d49bd-ea3d-4943-8bf6-dc0034aa6ec4
                  settings:
                    document_type_key: articles_of_association
              individualWithFile:
                summary: Create Document check on an individual with custom document type and some files
                description: Using the body parameter `DocumentCheckIndividualCreate`
                value:
                  individual_id: 4b36ce30-3d90-421a-b2d9-a046e5e4cfef
                  settings:
                    document_type_key: proof_of_address_document_key
                  data:
                    files:
                    - upload_ref: dG1wL2hlbGxvLWRvdGZpbGUtMTY3OTQ5ODQxMjcyNUZJUVFFLnBuZyxpbWFnZS9wbmcsaGVsbG8tZG90ZmlsZS5wbmc=
                    - upload_ref: dG1wL2hlbGxvLWRvdGZpbGUyLTE2Nzk0OTg0MTI3OTQyRklRUUUucG5nLGltYWdlL3BuZyxoZWxsby1kb3RmaWxlMi5wbmc=
              withDocumentAnalysis:
                summary: Create Document check on a company with automated document analysis
                description: Using the body parameter `DocumentCheckIndividualCreate`
                value:
                  company_id: de0d49bd-ea3d-4943-8bf6-dc0034aa6ec4
                  settings:
                    document_type_key: registration_certificate
                    document_analysis:
                      automatic_approval: true
                      automatic_rejection: false
                      parameters:
                        model: registration_certificate
                        max_age_in_days: 92
                        authorized_documents:
                        - kbis
                  data:
                    files:
                    - upload_ref: dG1wL2hlbGxvLWRvdGZpbGUtMTY3OTQ5ODQxMjcyNUZJUVFFLnBuZyxpbWFnZS9wbmcsaGVsbG8tZG90ZmlsZS5wbmc=
              withFraudAnalysis:
                summary: Create Document check on a company with fraud analysis
                description: Using the body parameter `DocumentCheckCompanyCreate`
                value:
                  company_id: de0d49bd-ea3d-4943-8bf6-dc0034aa6ec4
                  settings:
                    document_type_key: bank_details
                    fraud_analysis:
                      enabled: true
                  data:
                    files:
                    - upload_ref: dG1wL2hlbGxvLWRvdGZpbGUtMTY3OTQ5ODQxMjcyNUZJUVFFLnBuZyxpbWFnZS9wbmcsaGVsbG8tZG90ZmlsZS5wbmc=
      responses:
        '201':
          description: 'Document check has been created


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentCheck'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the body payload matches the expected schema\n  - When the number of `files` is invalid, must be between 0 and 10\n  - When one of the `upload_ref` is expired or invalid\n  "
      tags:
      - Document check
  /v1/checks/document/{id}/add_files:
    post:
      operationId: document-add-file
      summary: Add files
      description: 'Add some files to an existing Document check. Use Upload a file to get an `upload_ref`.


        ---


        #### See also

        Learn more about Document checks

        Learn more about Files'
      parameters:
      - name: id
        required: true
        in: path
        description: Id of the Document check
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentCheckAddFiles'
      responses:
        '201':
          description: 'File has been added to the Document check


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentCheck'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  - Make sure the body payload matches the expected schema\n  - When the number of `files` is invalid, must be between 1 and 10\n  - When one of the `upload_ref` is expired or invalid\n  "
        '404':
          description: No Document check can be found.
      tags:
      - Document check
  /v1/checks/document/{id}:
    get:
      operationId: document-get-one
      summary: Retrieve a Document check
      description: 'Returns detailed information about the specified Document check.


        ---


        #### See also

        Learn more about Document checks

        Learn more about Files'
      parameters:
      - name: id
        required: true
        in: path
        description: Id of the Document check
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: '**ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentCheck'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  "
        '404':
          description: No Document check can be found.
      tags:
      - Document check
  /v1/checks/document/{id}/force_review:
    post:
      operationId: document-force-review
      summary: Force review
      description: 'Force the manual review of a Document check in status `in_progress` with files.


        ---


        #### See also

        Learn more about Document checks'
      parameters:
      - name: id
        required: true
        in: path
        description: Id of the Document check
        schema:
          format: uuid
          type: string
      responses:
        '200':
          description: 'Status is set to `need_review`


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentCheck'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  - When there is no file for this check\n  - When the status is not `in_progress` or `need_review`\n  "
        '404':
          description: No Document check can be found.
      tags:
      - Document check
  /v1/checks/document/{id}/review:
    patch:
      operationId: document-review
      summary: Review a Document check
      description: 'Approve or reject a Document check. The Reviewer type will be set to `api`.


        ---


        #### See also

        Learn more about Document checks'
      parameters:
      - name: id
        required: true
        in: path
        description: Id of the Document check
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewCheckInput'
      responses:
        '200':
          description: 'Document check has been reviewed


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentCheck'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  - Make sure the body payload matches the expected schema\n  "
        '404':
          description: No Document check can be found.
      tags:
      - Document check
  /v1/document_types:
    get:
      operationId: document-type-get-many
      summary: List all document types
      description: 'Returns a list of all document types created in your Dotfile workspace.


        ---


        #### See also

        Learn more about Document check'
      parameters:
      - name: label
        required: false
        in: query
        description: "Filter items by the `label.{operator}` field.  \nYou can use the `eq`, `not_eq`, `like` and `ilike` operators, the `eq` operator being the default."
        schema:
          type: string
      - name: key
        required: false
        in: query
        description: "Filter items by the `key.{operator}` field.  \nYou can use the `eq`, `not_eq`, `like` and `ilike` operators, the `eq` operator being the default."
        schema:
          type: string
      - name: created_at
        required: false
        in: query
        description: "Filter items by the `created_at.{operator}` field.  \nYou can use the `eq`, `not_eq`, `gt`, `gte`, `lt` and `lte` operators, the `eq` operator being the default."
        schema:
          type: string
          pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,3})?(Z|([0-9]{2}:[0-9]{2}))?)?$
          example:
          - '2023-01-31'
          - '2023-01-31T13:30:00Z'
          - '2023-01-31T13:30:00.000Z'
          description: Date (`yyyy-MM-dd` eg `2023-01-31`) or date time (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`) in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
      - name: updated_at
        required: false
        in: query
        description: "Filter items by the `updated_at.{operator}` field.  \nYou can use the `eq`, `not_eq`, `gt`, `gte`, `lt` and `lte` operators, the `eq` operator being the default."
        schema:
          type: string
          pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,3})?(Z|([0-9]{2}:[0-9]{2}))?)?$
          example:
          - '2023-01-31'
          - '2023-01-31T13:30:00Z'
          - '2023-01-31T13:30:00.000Z'
          description: Date (`yyyy-MM-dd` eg `2023-01-31`) or date time (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`) in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)
      - name: include_archived
        required: false
        in: query
        description: "Include archived custom document types.  \nDefault is false"
        schema:
          type: boolean
      - name: sort
        required: false
        in: query
        description: "Use this parameter to sort query results.  \nIf not specified, sorted in _descending_ order with values of field `created_at`.  \nAvailable fields are `created_at`, `key`, `label` and `updated_at`."
        schema:
          default: created_at.desc
          type: string
        examples:
          created_at:
            summary: Sort by values of the "created_at" field in ascending order
            value: created_at
          key:
            summary: Sort by values of the "key" field in descending order
            value: key.desc
          label:
            summary: Sort by values of the "label" field in ascending order
            value: label
          updated_at:
            summary: Sort by values of the "updated_at" field in descending order
            value: updated_at.desc
          multiple:
            summary: Sort by values of multiple fields
            value: created_at,key.desc
      - name: page
        required: false
        in: query
        description: "Query response is paginated.  \nUse this parameter to choose which page you want to display.  \nPage index starts at 1 (the default)."
        schema:
          default: 1
          type: number
          minimum: 1
      - name: limit
        required: false
        in: query
        description: "Query response is paginated.  \nUse this parameter to choose the number of items per page.  \nLimit defaults to 20, maximum value is 100."
        schema:
          type: number
          default: 20
          minimum: 1
          maximum: 100
      responses:
        '200':
          description: 'List of document types created in the workspace


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentTypeList'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - One or multiple filtering parameters might be malformed. Make sure to use a supported operator and value for each filter.\n  - If specified, make sure the value of the `page` or `limit` query parameter are valid.\n  - Value of the `sort` parameter is invalid. Make sure the field name is supported, the sorting order is correctly specified, and a same field is not used multiple times for sorting.\n  "
      tags:
      - Document check
components:
  schemas:
    registration_certificate:
      type: object
      properties:
        model:
          type: string
          enum:
          - registration_certificate
        authorized_documents:
          type:
          - array
          - 'null'
          description: '`kbis` `sirene_extract` `pappers_extract` `inscription_rne` `infonet_extract` `repertoire_metiers_extract` `handelsregister` `visura_camerale` `other`'
          items:
            type: string
            enum:
            - kbis
            - sirene_extract
            - pappers_extract
            - inscription_rne
            - infonet_extract
            - repertoire_metiers_extract
            - handelsregister
            - visura_camerale
            - other
        max_age_in_days:
          type:
          - number
          - 'null'
          format: integer
      required:
      - model
    DocumentTypeList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CustomDocumentType'
        pagination:
          example:
            page: 1
            limit: 20
            count: 42
          allOf:
          - $ref: '#/components/schemas/Pagination'
      required:
      - data
      - pagination
    DocumentAnalysisIBANDetailedResults:
      type: object
      properties:
        valid_iban:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        valid_bic:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        name_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        iban_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        bic_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
      required:
      - valid_iban
      - valid_bic
      - name_matching
      - iban_matching
      - bic_matching
    DocumentAnalysisPromptInformation:
      type: object
      properties: {}
    ReviewCheckInput:
      type: object
      properties:
        action:
          type: string
          enum:
          - approve
          - reject
        comment:
          type:
          - string
          - 'null'
          description: Optional comment for the review.
        override:
          type: boolean
          description: Set to true to change the status of an already reviewed check (in status approved or rejected).
      required:
      - action
    DocumentCheckAddFiles:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: '#/components/schemas/DocumentCheckDataFileCreate'
        settings:
          allOf:
          - $ref: '#/components/schemas/DocumentCheckAddFilesSettings'
      required:
      - files
    DocumentCheckCompanyCreate:
      type: object
      properties:
        company_id:
          type: string
          format: uuid
        settings:
          description: Settings are optional and if not set it will use your workspace default settings
          allOf:
          - $ref: '#/components/schemas/DocumentCheckSettingsCreate'
        data:
          $ref: '#/components/schemas/DocumentCheckDataCreate'
      required:
      - company_id
      - settings
    iban:
      type: object
      properties:
        model:
          type: string
          enum:
          - iban
        iban_matching:
          type: boolean
          description: 'Verify if iban extracted on the document match entity `banking_information.iban`. Default: `false`'
        bic_matching:
          type: boolean
          description: 'Verify if bic extracted on the document match entity `banking_information.bic`. Default: `false`'
      required:
      - model
    DocumentCheckDataSettingsFraudAnalysis:
      type: object
      properties:
        enabled:
          type: boolean
          description: Enable or disable fraud analysis for this document
          default: false
      required:
      - enabled
    DocumentCheckIndividualCreate:
      type: object
      properties:
        individual_id:
          type: string
          format: uuid
        settings:
          description: Settings are optional and if not set it will use your workspace default settings
          allOf:
          - $ref: '#/components/schemas/DocumentCheckSettingsCreate'
        data:
          $ref: '#/components/schemas/DocumentCheckDataCreate'
      required:
      - individual_id
      - settings
    CustomDocumentType:
      type: object
      properties:
        id:
          type: string
          format: uuid
        label:
          type: string
        key:
          type: string
          description: "Unique identifier key.  \nFormat `/^[a-z][a-z_0-9]*$/`  \nMust be unique"
          pattern: /^[a-z][a-z_0-9]*$/
          example: some_key
        target_entities:
          type: array
          items:
            type: string
            enum:
            - company
            - individual
        is_internal:
          type: boolean
        created_at:
          type: string
          format: date-time
          description: "Creation date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
        updated_at:
          type: string
          format: date-time
          description: "Latest update date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
        archived_at:
          type:
          - string
          - 'null'
          format: date-time
          description: "Archival date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
      required:
      - id
      - label
      - key
      - target_entities
      - is_internal
      - created_at
      - updated_at
      - archived_at
    DocumentCheckAddFilesSettings:
      type: object
      properties:
        document_analysis:
          allOf:
          - $ref: '#/components/schemas/DocumentCheckDataSettingsDocumentAnalysis'
      required:
      - document_analysis
    DocumentDataSettings:
      type: object
      properties:
        document_type:
          description: Document type of this check
          allOf:
          - $ref: '#/components/schemas/CustomDocumentType'
        document_type_key:
          type: string
          description: Key of the document type of this check
        document_analysis:
          allOf:
          - $ref: '#/components/schemas/DocumentCheckDataSettingsDocumentAnalysis'
      required:
      - document_type
      - document_type_key
      - document_analysis
    proof_of_address:
      type: object
      properties:
        model:
          type: string
          enum:
          - proof_of_address
        authorized_documents:
          type:
          - array
          - 'null'
          description: '`energy_bill` `telco_bill` `official_document` `other`'
          items:
            type: string
            enum:
            - energy_bill
            - telco_bill
            - official_document
            - other
        max_age_in_days:
          type:
          - number
          - 'null'
          format: integer
      required:
      - model
    DocumentAnalysisIBANInformation:
      type: object
      properties:
        holder_name:
          type:
          - string
          - 'null'
        bank_name:
          type:
          - string
          - 'null'
        iban:
          type:
          - string
          - 'null'
        bic:
          type:
          - string
          - 'null'
      required:
      - holder_name
      - bank_name
      - iban
      - bic
    Pagination:
      type: object
      properties:
        page:
          type: number
          description: Current page number (defined in query parameter)
          default: 1
        limit:
          type: number
          description: Item count per page (defined in query parameter)
          default: 20
        count:
          type: number
          description: Total items count
          example: 42
      required:
      - page
      - limit
      - count
    DocumentAnalysisRegistrationCertificateInformation:
      type: object
      properties:
        name:
          type:
          - string
          - 'null'
        registration_number:
          type:
          - string
          - 'null'
        registration_city:
          type:
          - string
          - 'null'
        address:
          type:
          - string
          - 'null'
        country:
          type:
          - string
          - 'null'
        issuing_date:
          type:
          - string
          - 'null'
          format: date
          description: Date in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)(`yyyy-MM-dd` eg `2023-01-31`)
        document_type:
          type:
          - string
          - 'null'
          enum:
          - kbis
          - sirene_extract
          - pappers_extract
          - inscription_rne
          - infonet_extract
          - repertoire_metiers_extract
          - handelsregister
          - visura_camerale
          - other
        other_document_type:
          type:
          - string
          - 'null'
          description: Document type found for "other" category.
      required:
      - name
      - registration_number
      - registration_city
      - address
      - country
      - issuing_date
      - document_type
      - other_document_type
    DocumentCheckSettingsCreate:
      type: object
      properties:
        document_type_key:
          type: string
          description: 'Use your custom document type key or default document type. i.e. `kbis_document_type` or `registration_certificate` '
        document_analysis:
          allOf:
          - $ref: '#/components/schemas/DocumentCheckDataSettingsDocumentAnalysis'
        fraud_analysis:
          description: Fraud analysis settings. Document fraud analysis is billed on usage. Ask your customer support representative or sales representative if you want more details on the pricing.
          allOf:
          - $ref: '#/components/schemas/DocumentCheckDataSettingsFraudAnalysis'
      required:
      - document_type_key
    DocumentAnalysisPromptDetailedResults:
      type: object
      properties: {}
    DocumentAnalysisProofOfAddressDetailedResults:
      type: object
      properties:
        valid_age_in_days:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        address_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        name_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        valid_document_type:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
      required:
      - valid_age_in_days
      - address_matching
      - name_matching
      - valid_document_type
    DocumentCheckDataInformation:
      type: object
      properties:
        expiration_date:
          type:
          - string
          - 'null'
          format: date
          description: Date in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)(`yyyy-MM-dd` eg `2023-01-31`)
        document_analysis:
          oneOf:
          - $ref: '#/components/schemas/DocumentAnalysisRegistrationCertificateInformation'
            title: Registration Certificate
          - $ref: '#/components/schemas/DocumentAnalysisIBANInformation'
            title: IBAN
          - $ref: '#/components/schemas/DocumentAnalysisProofOfAddressInformation'
            title: Proof of Address
          - $ref: '#/components/schemas/DocumentAnalysisPromptInformation'
            title: Prompt
          discriminator:
            propertyName: model
      required:
      - expiration_date
      - document_analysis
    prompt:
      type: object
      properties:
        model:
          type: string
          enum:
          - prompt
        prompt:
          type: string
          description: Prompt used for document analysis
      required:
      - model
      - prompt
    DocumentAnalysisRegistrationCertificateDetailedResults:
      type: object
      properties:
        valid_age_in_days:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        address_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        registration_number_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        name_matching:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
        valid_document_type:
          $ref: '#/components/schemas/DocumentAnalysisDetailedResult'
      required:
      - valid_age_in_days
      - address_matching
      - registration_number_matching
      - name_matching
      - valid_document_type
    NestedUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
      required:
      - id
      - first_name
      - last_name
      - email
    DocumentAnalysisProofOfAddressInformation:
      type: object
      properties:
        issuing_date:
          type:
          - string
          - 'null'
          format: date
          description: Date in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)(`yyyy-MM-dd` eg `2023-01-31`)
        address:
          type:
          - string
          - 'null'
        name:
          type:
          - string
          - 'null'
        document_type:
          type:
          - string
          - 'null'
          enum:
          - energy_bill
          - telco_bill
          - official_document
          - other
        other_document_type:
          type:
          - string
          - 'null'
          description: Document type found for "other" category.
        country:
          type:
          - string
          - 'null'
        issuer:
          type:
          - string
          - 'null'
          description: Issuer of the document
      required:
      - issuing_date
      - address
      - name
      - document_type
      - other_document_type
      - country
      - issuer
    DocumentCheckDataCreate:
      type: object
      properties:
        files:
          type: array
          items:
            $ref: '#/components/schemas/DocumentCheckDataFileCreate'
      required:
      - files
    DocumentCheckDataSettingsDocumentAnalysis:
      type: object
      properties:
        automatic_rejection:
          type: boolean
        automatic_approval:
          type: boolean
        parameters:
          oneOf:
          - $ref: '#/components/schemas/registration_certificate'
            title: Registration Certificate
          - $ref: '#/components/schemas/iban'
            title: IBAN
          - $ref: '#/components/schemas/proof_of_address'
            title: Proof of Address
          - $ref: '#/components/schemas/prompt'
            title: Prompt
          discriminator:
            propertyName: model
      required:
      - automatic_rejection
      - automatic_approval
      - parameters
    DocumentAnalysisDetailedResult:
      type: object
      properties:
        result:
          type:
          - string
          - 'null'
          enum:
          - approved
          - rejected
          - error
        expected:
          type:
          - string
          - 'null'
        received:
          type:
          - string
          - 'null'
      required:
      - result
      - expected
      - received
    Review:
      type: object
      properties:
        comment:
          type:
          - string
          - 'null'
        reviewed_at:
          type:
          - string
          - 'null'
          format: date-time
          description: Date time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)
        reviewer_type:
          type:
          - string
          - 'null'
          enum:
          - user
          - system
          - api
        user:
          allOf:
          - $ref: '#/components/schemas/NestedUser'
      required:
      - comment
      - reviewed_at
      - reviewer_type
      - user
    DocumentCheckDataDetailedResults:
      type: object
      properties:
        document_analysis:
          oneOf:
          - $ref: '#/components/schemas/DocumentAnalysisRegistrationCertificateDetailedResults'
            title: Registration Certificate
          - $ref: '#/components/schemas/DocumentAnalysisIBANDetailedResults'
            title: IBAN
          - $ref: '#/components/schemas/DocumentAnalysisProofOfAddressDetailedResults'
            title: Proof of Address
          - $ref: '#/components/schemas/DocumentAnalysisPromptDetailedResults'
            title: Prompt
          discriminator:
            propertyName: model
      required:
      - document_analysis
    DocumentCheckData:
      type: object
      properties:
        result:
          type:
          - string
          - 'null'
          enum:
          - approved
          - rejected
          - error
        settings:
          $ref: '#/components/schemas/DocumentDataSettings'
        review:
          $ref: '#/components/schemas/Review'
        detailed_results:
          deprecated: true
          allOf:
          - $ref: '#/components/schemas/DocumentCheckDataDetailedResults'
        document_file_ids:
          type: array
          items:
            type: string
            format: uuid
        information:
          $ref: '#/components/schemas/DocumentCheckDataInformation'
      required:
      - result
      - settings
      - review
      - detailed_results
      - document_file_ids
      - information
    DocumentCheckDataFileCreate:
      type: object
      properties:
        upload_ref:
          type: string
      required:
      - upload_ref
    DocumentCheck:
      type: object
      properties:
        id:
          type: string
          format: uuid
        company_id:
          type:
          - string
          - 'null'
          format: uuid
        individual_id:
          type:
          - string
          - 'null'
          format: uuid
        is_internal:
          type: boolean
        status:
          type: string
          enum:
          - in_progress
          - need_review
          - processing
          - approved
          - rejected
          - expired
          description: ℹ️ Check status `expired` is deprecated and will be removed Q1'25. It will be replaced with an expired flag.
        type:
          type: string
          default: document
          enum:
          - document
        subtype:
          type: string
          description: Contains `"document_type:{settings.document_type_key}"`
        last_activity_at:
          type: string
          format: date-time
          description: "Latest activity date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
        data:
          $ref: '#/components/schemas/DocumentCheckData'
      required:
      - id
      - company_id
      - individual_id
      - is_internal
      - status
      - type
      - subtype
      - last_activity_at
      - data
  securitySchemes:
    DotfileAPIKey:
      type: apiKey
      in: header
      name: X-DOTFILE-API-KEY
      description: Configure your api key in the Workspace settings
x-uploaded-at: '2026-08-14T14:05:07.336Z'
x-commit-sha: f460fa65a5cc33cf4211bbcee7818f93d5b9e8de
