openapi: 3.2.0
info:
  title: ⚙️ API specifications Notes API
  description: Dotfile public API documentation
  version: v1
  contact: {}
servers:
- url: https://api.dotfile.com
  description: Production environment
security:
- DotfileAPIKey: []
tags:
- name: Notes
paths:
  /v1/notes:
    post:
      operationId: note-create-one-note
      summary: Create a note
      description: Create a note in a case.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteCreate'
            examples:
              note_plain_text:
                summary: Create a plain text note
                value:
                  case_id: ba883bef-60fd-42d0-a447-7b7c987c3155
                  content: This is a note!
              note_html:
                summary: Create a HTML note
                value:
                  case_id: ba883bef-60fd-42d0-a447-7b7c987c3155
                  content: <p>This is a <strong>important</strong><br /></p><ul><li>Some bullet point</li><li><i>supporting some format</i></li></ul>
              note_html_with_link:
                summary: Create a HTML note with link
                value:
                  case_id: ba883bef-60fd-42d0-a447-7b7c987c3155
                  content: <p>This is a <a href="https://dotfile.com" target="_blank" rel="noreferrer">link</a></p>
              note_html_with_mention:
                summary: Create a HTML note with mention
                value:
                  case_id: ba883bef-60fd-42d0-a447-7b7c987c3155
                  content: <p>This will mention <span data-type="mention" data-id="user:d86b5c10-db43-4021-86b2-6c27df7819b0"></span> and sent him a notification</p>
      responses:
        '201':
          description: 'Note has been created in the case


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  - Make sure the body payload matches the expected schema\n  - Maximum items reached (default: 25). Contact us at support@dotfile.com if you need more items.\n  "
        '404':
          description: No case can be found.
      tags:
      - Notes
  /v1/notes/{id}/comments:
    post:
      operationId: note-create-one-note-comment
      summary: Create a note comment
      description: Create a comment on a note.
      parameters:
      - name: id
        required: true
        in: path
        description: Id of the note comment
        schema:
          format: uuid
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NoteCommentCreate'
            examples:
              comment_plain_text:
                summary: Create a plain text comment
                value:
                  content: This is a comment!
              comment_html:
                summary: Create a HTML comment
                value:
                  content: <p>This is a <strong>important</strong><br /></p><ul><li>Some bullet point</li><li><i>supporting some format</i></li></ul>
              comment_html_with_link:
                summary: Create a HTML comment with link
                value:
                  content: <p>This is a <a href="https://dotfile.com" target="_blank" rel="noreferrer">link</a></p>
              comment_html_with_mention:
                summary: Create a HTML comment with mention
                value:
                  content: <p>This will mention <span data-type="mention" data-id="user:d86b5c10-db43-4021-86b2-6c27df7819b0"></span> and sent him a notification</p>
      responses:
        '201':
          description: 'Comment has been created on the note


            **ℹ️ Click to see full payload**'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteComment'
        '400':
          description: "The request is either malformed or contain invalid parameters.\n\n  - Make sure the identifier specified in the URL is a valid UUID\n  - Make sure the body payload matches the expected schema\n  - Maximum items reached (default: 50). Contact us at support@dotfile.com if you need more items.\n  "
        '404':
          description: No note can be found.
      tags:
      - Notes
components:
  schemas:
    NoteCreate:
      type: object
      properties:
        case_id:
          type: string
          format: uuid
          description: Case id where the note is created
        content:
          type: string
          description: "\n  You can format with a subset of html:\n  - Allowed tags are `p`, `b`, `i`, `em`, `strong`, `a` with attributes `href`, `target` and `rel`, `li`, `ul`, `span` with attributes `data-type`, `data-id` and `data-label`, `br` and `hr`.\n  - Invalid tag or attribute will be stripped out.\n  - URL will be transformed into link. `target` and `rel` will be automatically set.\n  - Line break `\\n` will be replaced by `<br />`.\n  - A `<p>` will be added if the content doesn't start with a `<p>` or a `<ul>` tag\n  - You can mention an user with `<span data-type=\"mention\" data-id=\"user:d86b5c10-db43-4021-86b2-6c27df7819b0\"></span>`. `data-label` and inner text will be automatically set and the user will receive a notification.\n  - Ignoring html tag, the content must be at most `3000`\n  "
      required:
      - case_id
      - content
    NoteComment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        note_id:
          type: string
          format: uuid
          description: Comment's note id
        content:
          type: string
          description: HTML content
        author:
          allOf:
          - $ref: '#/components/schemas/NestedUser'
        author_type:
          type: string
          enum:
          - user
          - api
        created_at:
          type: string
          format: date-time
          description: "Creation date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
        updated_at:
          type: string
          format: date-time
          description: "Update date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
      required:
      - id
      - note_id
      - content
      - author
      - author_type
      - created_at
      - updated_at
    NoteCommentCreate:
      type: object
      properties:
        content:
          type: string
          description: "\n  You can format with a subset of html:\n  - Allowed tags are `p`, `b`, `i`, `em`, `strong`, `a` with attributes `href`, `target` and `rel`, `li`, `ul`, `span` with attributes `data-type`, `data-id` and `data-label`, `br` and `hr`.\n  - Invalid tag or attribute will be stripped out.\n  - URL will be transformed into link. `target` and `rel` will be automatically set.\n  - Line break `\\n` will be replaced by `<br />`.\n  - A `<p>` will be added if the content doesn't start with a `<p>` or a `<ul>` tag\n  - You can mention an user with `<span data-type=\"mention\" data-id=\"user:d86b5c10-db43-4021-86b2-6c27df7819b0\"></span>`. `data-label` and inner text will be automatically set and the user will receive a notification.\n  - Ignoring html tag, the content must be at most `3000`\n  "
      required:
      - content
    NestedUser:
      type: object
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
      required:
      - id
      - first_name
      - last_name
      - email
    Note:
      type: object
      properties:
        id:
          type: string
          format: uuid
        case_id:
          type: string
          format: uuid
          description: Note's case id
        content:
          type: string
          description: HTML content
        comments:
          description: Maximum of 50 comments per note.
          type: array
          items:
            $ref: '#/components/schemas/NoteComment'
        author:
          allOf:
          - $ref: '#/components/schemas/NestedUser'
        author_type:
          type: string
          enum:
          - user
          - api
        created_at:
          type: string
          format: date-time
          description: "Creation date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
        updated_at:
          type: string
          format: date-time
          description: "Update date  \nDate time in format [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (`yyyy-MM-ddTHH:mm:ss.S+X` eg `2023-01-31T13:30:00.000Z`)"
      required:
      - id
      - case_id
      - content
      - comments
      - author
      - author_type
      - created_at
      - updated_at
  securitySchemes:
    DotfileAPIKey:
      type: apiKey
      in: header
      name: X-DOTFILE-API-KEY
      description: Configure your api key in the Workspace settings
x-uploaded-at: '2026-08-14T14:05:07.336Z'
x-commit-sha: f460fa65a5cc33cf4211bbcee7818f93d5b9e8de
